(function(b){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,a=d?d("DetailPageLayoutAssets",""):c;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,c,d){b.when("A","ready").execute(function(a){var b,d=a.$;a.on("a:expander:zones_progressive_disclosure_expander:toggle:collapse",function(a){(a=d("#dp-pr-top"))&&a.length||c.scrollTo({top:b})});a.on("a:expander:zones_progressive_disclosure_expander:toggle:expand",function(a){b=d(c).scrollTop()})})});
/* ******** */
(function(l){var m=window.AmazonUIPageJS||window.P,n=m._namespace||m.attributeErrors,c=n?n("DetailPageMobileIconFarmAssets@common","DetailPageMobileIconFarm"):m;c.guardFatal?c.guardFatal(l)(c,window):c.execute(function(){l(c,window)})})(function(l,m,n){l.when("A","ready").register("get-icon-farm-page-state",function(c){return{parseJSON:function(e,b){b="iconfarm-state-"+b;var d='script[data-a-state\x3d"{"key":"'+b+'"}"]',a;try{a=c.$("#"+e).find(d).html()}catch(g){console.log(g.message)}a?e=c.$.parseJSON(a):
(c.state.parse(),e=c.state(b));return e}}});l.declare("icon-farm-mod-constants",{selector:{BUYBOX_ACCORDION:"#buybox .a-accordion",BUYBOX_ACCORDION_ACTIVE:"#buybox .a-accordion-active",iconfarm:"#iconfarmv2_feature_div .offersConsistencyEnabled"}});l.declare("iconfarm-metrics-constants",{ICON_FARM_FEATURE_DIV:"iconFarm_feature_div",ICON_FARM_PAGE_STATE_HOLDER_DIV:"iconfarm-pagestate-holder",METRIC_TYPE:{GLANCE_VIEW:"GLANCE_VIEW",ICON_CLICK:"ICON_CLICK",SECONDARY_PAGE_OPEN:"SECONDARY_PAGE_OPEN",SECONDARY_PAGE_CLOSE:"SECONDARY_PAGE_CLOSE",
FULL_RETURN_POLICY:"FULL_RETURN_POLICY",PAGE_DATA_MISSING:"PAGE_DATA_MISSING",ABSENT:"ABSENT"},REF_MARKER_PREFIX:{ICON_FARM_WIDGET:"iconfarm_wid",AMAZON_DELIVERED:"iconfarm_ad",RETURNS_POLICY:"iconfarm_rp",PAY_ON_DELIVERY:"iconfarm_pod",WARRANTY:"iconfarm_wr",EASY_CARE:"iconfarm_ec",AMAZON_PROTECT:"iconfarm_ap",NO_CONTACT_DELIVERY:"iconfarm_ncd",GENERIC_RETURN_POLICY:"iconfarm_grp",MULTIPLE_SPECIFIC_RETURN_POLICY:"iconfarm_msrp",SINGLE_SPECIFIC_RETURN_POLICY:"iconfarm_ssrp",PAYMENTS_AND_SECURITY:"iconfarm_ps",
PAY_ON_DELIVERY_ACTIVE:"iconfarm_pod_active",PAY_ON_DELIVERY_INACTIVE:"iconfarm_pod_inactive",WARRANTY_EU:"iconfarm_wr_eu",AMAZON_MANAGED_DELIVERY:"iconfarm_amd",AMAZON_DELIVERED_MENA:"iconfarm_ad_mena",SAFE_PAYMENTS:"iconfarm_sp",STATIC_RETURNS_POLICY:"iconfarm_srp",GENERIC_RETURNS_POLICY:"iconfarm_grp",SUPPORT_POLICY:"iconfarm_supp",WARRANTY360:"iconfarm_wr360",WORRY_FREE_GUARANTEE_JP:"iconfarm_wfg_jp",WARRANTY_JP:"iconfarm_wr_jp",DELIVERY_JP:"iconfarm_dl_jp",RETURN_POLICY_JP:"iconfarm_rp_jp",SMALL_BUSINESS_JP:"iconfarm_sb_jp",
DELIVERY_HIT:"iconfarm_dh",WARRANTY_HIT:"iconfarm_wh",RETURN_POLICY_HIT:"iconfarm_rph",CUSTOMER_SUPPORT:"iconfarm_cs",SERVICE:"iconfarm_serv",FREE_DELIVERY:"iconfarm_fd",TOP_BRAND:"iconfarm_tb"},REF_MARKER_SUFFIX:{GLANCE_VIEW:"_gv",ICON_CLICK:"_clk",SECONDARY_PAGE_OPEN:"_sp_op",SECONDARY_PAGE_CLOSE:"_sp_cl",FULL_RETURN_POLICY:"_frp",ABSENT:"_noavail"},NEXUS_CONFIG:{NEXUS_PRODUCER_ID:"a2i-dpx",NEXUS_SCHEMA_ID:"a2i.dpx.WidgetImpressions.3"},LOGGER_CONFIG:{NEXUS_LOGGER:"nexus"}});l.when("A","iconfarm-return-policy-metric-logger",
"iconfarm-pay-on-delivery-metric-logger","iconfarm-default-metric-logger").register("iconfarm-icon-metric-factory",function(c,e,b,d){return{getIconMetric:function(a){switch(a){case "RETURNS_POLICY":return e;case "PAY_ON_DELIVERY":return b;default:return d}}}});l.when("A","iconfarm-metrics-constants","get-icon-farm-page-state","iconfarm-icon-metric-factory","ready").register("iconfarm-metricLogger",function(c,e,b,d){return{log:function(a,g,h,f){if(a&&g&&null!==h&&e.REF_MARKER_PREFIX[a]&&e.REF_MARKER_SUFFIX[g]){var k=
b.parseJSON(e.ICON_FARM_PAGE_STATE_HOLDER_DIV+"-"+h,h);k?d.getIconMetric(a).log(a,g,h,c.$.extend(!0,{asin:k.asin,merchantId:k.merchantId,remoteAddress:k.remoteAddress,isInternal:k.isInternal,isRobot:k.isRobot,numOfShownIcons:k.numOfShownIcons,buyingOptionIndex:h},f)):console.warn("iconfarm state may not be available")}}}});l.when("A","ready").register("iconfarm-postmetric",function(){return{postCountMetric:function(c){if("undefined"!==typeof c){var e=m.ue;if(e){var b=e.count(c)||0;e.count(c,b+1)}}},
postTimeMetric:function(c,e){if("undefined"!==typeof c&&"undefined"!==typeof e){var b=m.ue;b&&b.count(c,e)}}}});l.when("A","ready").register("iconfarm-metric-cache",function(c){var e=[],b=function(a){if(!d(a))return!1;var b=!1;c.each(e,function(c,d){c.asin===a.asin&&c.merchantId===a.merchantId&&c.ref===a.ref&&c.loggerType===a.loggerType&&c.buyingOptionIndex===a.buyingOptionIndex&&(b=!0)});return b},d=function(a){return a&&a.asin&&a.merchantId&&a.ref&&a.loggerType&&null!==a.buyingOptionIndex};return{isPresent:b,
add:function(a){return d(a)?b(a)?!1:(e.push(a),!0):!1},reset:function(){e=[]}}});"use strict";l.when("A","iconfarm-metric-cache","iconfarm-metrics-constants","ready").register("iconfarm-Nexus-Service",function(c,e,b){return{log:function(d){if(e.add(d)){var a={};a.producerId=b.NEXUS_CONFIG.NEXUS_PRODUCER_ID;a.schemaId=b.NEXUS_CONFIG.NEXUS_SCHEMA_ID;a.refMarker=d.ref;a.pageAsin=d.asin;a.pageType=c.capabilities?c.capabilities.mobile?c.capabilities.isAmazonApp?"DetailWebView":"DetailAW":"Detail":"";a.subPageType=
"IconFarm";a.server=m?m.ue_sn:"";a.merchantId=d.merchantId;a.remoteAddress=d.remoteAddress;a.isInternal=d.isInternal?1:0;a.isRobot=d.isRobot?1:0;var g={};g.numOfShownIcons=d.numOfShownIcons;g.buyingOptionIndex=d.buyingOptionIndex;d=JSON.stringify(g);a.additionalRequestData=d;if(d=m.ue)try{d.event&&d.event(a,b.NEXUS_CONFIG.NEXUS_PRODUCER_ID,b.NEXUS_CONFIG.NEXUS_SCHEMA_ID)}catch(h){d.count("NexusLoggerFailure",1)}}}}});l.when("A","iconfarm-Nexus-Service","iconfarm-metrics-constants","iconfarm-postmetric",
"ready").register("iconfarm-default-metric-logger",function(c,e,b,d){return{log:function(a,g,h,f){h=JSON.parse(JSON.stringify(f));e.log(c.$.extend(!0,h,{ref:b.REF_MARKER_PREFIX[a]+b.REF_MARKER_SUFFIX[g],loggerType:b.LOGGER_CONFIG.NEXUS_LOGGER}));d.postCountMetric(b.REF_MARKER_PREFIX[a]+b.REF_MARKER_SUFFIX[g])}}});l.when("A","iconfarm-Nexus-Service","iconfarm-metrics-constants","iconfarm-postmetric","get-icon-farm-page-state","ready").register("iconfarm-return-policy-metric-logger",function(c,e,b,
d,a){return{log:function(g,h,f,k){a:{if((f=a.parseJSON(b.ICON_FARM_PAGE_STATE_HOLDER_DIV+"-"+f,f))&&f.RETURNS_POLICY&&f.RETURNS_POLICY.secondaryViewData&&f.RETURNS_POLICY.secondaryViewData.glLevelReturnPolicies)switch(f.RETURNS_POLICY.secondaryViewData.glLevelReturnPolicies.length){case 0:f="GENERIC_RETURN_POLICY";break a;case 1:f="SINGLE_SPECIFIC_RETURN_POLICY";break a;default:f="MULTIPLE_SPECIFIC_RETURN_POLICY";break a}f=void 0}g=f||g;k=JSON.parse(JSON.stringify(k));e.log(c.$.extend(!0,k,{ref:b.REF_MARKER_PREFIX[g]+
b.REF_MARKER_SUFFIX[h],loggerType:b.LOGGER_CONFIG.NEXUS_LOGGER}));d.postCountMetric(b.REF_MARKER_PREFIX[g]+b.REF_MARKER_SUFFIX[h])}}});l.when("A","iconfarm-Nexus-Service","iconfarm-metrics-constants","iconfarm-postmetric","get-icon-farm-page-state","ready").register("iconfarm-pay-on-delivery-metric-logger",function(c,e,b,d,a){return{log:function(g,h,f,k){f=(f=a.parseJSON(b.ICON_FARM_PAGE_STATE_HOLDER_DIV+"-"+f,f))&&f.PAY_ON_DELIVERY&&f.PAY_ON_DELIVERY.isEligible?f.PAY_ON_DELIVERY.isEligible?"PAY_ON_DELIVERY_ACTIVE":
"PAY_ON_DELIVERY_INACTIVE":void 0;g=f||g;k=JSON.parse(JSON.stringify(k));e.log(c.$.extend(!0,k,{ref:b.REF_MARKER_PREFIX[g]+b.REF_MARKER_SUFFIX[h],loggerType:b.LOGGER_CONFIG.NEXUS_LOGGER}));d.postCountMetric(b.REF_MARKER_PREFIX[g]+b.REF_MARKER_SUFFIX[h])}}})});
/* ******** */
(function(e){var k=window.AmazonUIPageJS||window.P,g=k._namespace||k.attributeErrors,a=g?g("DetailPageMobileIconFarmAssets@desktop","DetailPageMobileIconFarm"):k;a.guardFatal?a.guardFatal(e)(a,window):a.execute(function(){e(a,window)})})(function(e,k,g){e.when("A","a-popover","icon-farm-constants","iconfarm-metricLogger","iconfarm-metrics-constants","icon-farm-web-mod-util","ready").register("icon-farm-desktop-popover",function(a,l,b,c,d,f){var h=function(b){var h=b.data("name");a.off("a:popover:beforeShow:"+
h);a.on("a:popover:beforeShow:"+h,function(a){a=f.getCurrentBuyingOptionIndex();c.log(h,d.METRIC_TYPE.ICON_CLICK,a);c.log(h,d.METRIC_TYPE.SECONDARY_PAGE_OPEN,a)});a.off("a:popover:beforeHide:"+h);a.on("a:popover:beforeHide:"+h,function(a){a=f.getCurrentBuyingOptionIndex();c.log(h,d.METRIC_TYPE.SECONDARY_PAGE_CLOSE,a)})};return{init:function(){for(var c=a.$(b.ICON_FARM_CONTAINER_CLASS),f=0;f<c.length;f++){var d=a.$(c[f]),e=d.data(b.TYPE_PARAM);if(e&&e===b.TYPE_PARAM_VALUE_CUSTOM_POP_OVER){var e=d,
g=a.$("#"+e.data(b.POPOVER_CONTENT_PARAM)),g={activate:b.POPOVER_ACTIVATION,position:b.POPOVER_POSITION,width:b.POPOVER_WIDTH,inlineContent:g.html(),name:e.data("name")};l.create(e,g);h(d)}}}}});e.when("A","get-icon-farm-page-state","icon-farm-constants","iconfarm-metricLogger","iconfarm-metrics-constants","icon-farm-web-mod-util","ready").register("icon-farm-desktop-returns-policy",function(a,e,b,c,d,f){a.declarative("returns-policy-url","click",function(a){a=f.getCurrentBuyingOptionIndex();c.log("RETURNS_POLICY",
d.METRIC_TYPE.FULL_RETURN_POLICY,a);a=e.parseJSON(b.ICON_FARM_PAGE_STATE_HOLDER_DIV+"-"+a,a);k.open(a.RETURNS_POLICY.genericReturnPolicyURL,"_blank")});a.off("a:popover:beforeShow:return-policy-secondary-view");a.on("a:popover:beforeShow:return-policy-secondary-view",function(a){a=f.getCurrentBuyingOptionIndex();c.log("RETURNS_POLICY",d.METRIC_TYPE.ICON_CLICK,a);c.log("RETURNS_POLICY",d.METRIC_TYPE.SECONDARY_PAGE_OPEN,a)});a.off("a:popover:beforeHide:return-policy-secondary-view");a.on("a:popover:beforeHide:return-policy-secondary-view",
function(a){a=f.getCurrentBuyingOptionIndex();c.log("RETURNS_POLICY",d.METRIC_TYPE.SECONDARY_PAGE_CLOSE,a)});return{init:function(){}}});e.when("A","IconFarmPageStateParserService","icon-farm-desktop-popover","icon-farm-desktop-returns-policy","iconfarm-metricLogger","icon-farm-constants","iconfarm-metrics-constants","iconfarm-metric-cache","icon-farm-web-mod-util","icon-farm-change-buying-option","atf","ready").execute(function(a,l,b,c,d,f,h,g,k,q){function m(){g.reset();a.loadImageManually(a.$(".icon-box"));
b.init();c.init();q.init();for(var f=0;f<n;f++)r(f)}var n=k.getBuyingOptionCounts(),r=function(f){var b="#icon-farm-widget-"+f,c=a.$(b);c&&c.length?d.log("ICON_FARM_WIDGET",h.METRIC_TYPE.GLANCE_VIEW,f):d.log("ICON_FARM_WIDGET",h.METRIC_TYPE.ABSENT,f);(b=a.$(b+" .icon-container"))&&b.length&&b.each(function(){d.log(a.$(this).data("name"),h.METRIC_TYPE.GLANCE_VIEW,f)})};m();a.on("a:pageUpdate",function(){var b;a:{try{if(a.$("#"+f.ICON_FARM_V2_FEATURE_DIV).find("script").length){b=f.ICON_FARM_V2_FEATURE_DIV;
break a}if(a.$("#"+f.ICON_FARM_V2_PRIMARY_FEATURE_DIV).find("script").length){b=f.ICON_FARM_V2_PRIMARY_FEATURE_DIV;break a}d.log("ICON_FARM_WIDGET",h.PAGE_DATA_MISSING,0)}catch(c){e.log(c,"ERROR","DetailPageMobileIconFarm")}b=void 0}if(b){for(var g=0;g<n;g++)if(l.isNewState(b,f.ICON_FARM_STATE+"-"+g)){var p=l.processState(b,f.ICON_FARM_STATE+"-"+g);if(a.objectIsEmpty(p))return}m()}})});e.declare("icon-farm-constants",{ICON_FARM_FEATURE_DIV:"iconFarm_feature_div",ICON_FARM_V2_FEATURE_DIV:"iconfarmv2_feature_div",
ICON_FARM_V2_PRIMARY_FEATURE_DIV:"iconFarmV2InsidePrimary_feature_div",ICON_FARM_PAGE_STATE_HOLDER_DIV:"iconfarm-pagestate-holder",ICON_FARM_CONTAINER_CLASS:".icon-container",ICON_FARM_SECONDARY_VIEW_HOLDER_ID:"#icon-farm-secondary-view-holder",ICON_FARM_STATE:"iconfarm-state",POPOVER_ACTIVATION:"onclick",POPOVER_POSITION:"triggerBottom",POPOVER_WIDTH:"533",POPOVER_CONTENT_PARAM:"iconContent",TYPE_PARAM:"type",TYPE_PARAM_VALUE:"bottom-sheet",TYPE_PARAM_VALUE_CUSTOM_POP_OVER:"custom-pop-over"});(function(){e.when("A",
"atf","ready").register("IconFarmPageStateParserService",function(a){function e(b,c){c='script[data-a-state\x3d"'+JSON.stringify({key:c})+'"]';return a.$("#"+b).find(c)}return{processState:function(b,c){var d;try{var f=e(b,c),h=f[0];d=f.html();var g=a.parseJSON(d);a.state(c,g);a.$.data(h,"state_processed",!0);return g}catch(k){console.log(k)}return a.state(c)},isNewState:function(b,c){try{return!a.$.data(e(b,c)[0],"state_processed")}catch(d){console.warn("Unable to determine state status",d)}return!1}}})})();
"use strict";e.when("A","icon-farm-mod-constants").register("icon-farm-web-mod-util",function(a,e){return{getBuyingOptionCounts:function(){if(!a.$(e.selector.iconfarm).length)return 1;var b=a.$(e.selector.BUYBOX_ACCORDION);if(0===b.length)return 1;b=b[0];if(a.$(e.selector.iconfarm).length){for(var b=b.children,c=0,d=0;d<b.length;d++)var f=a.$(b[d]).attr("data-buying-option-index"),c=Math.max(c,f);b=c}else b=0;return b+1},getCurrentBuyingOptionIndex:function(){var b=0;if(!a.$(e.selector.iconfarm).length)return 0;
var c=a.$(e.selector.BUYBOX_ACCORDION_ACTIVE);c.length&&(b=c.index());return b}}});e.when("A","icon-farm-mod-constants","icon-farm-web-mod-util","ready").register("icon-farm-change-buying-option",function(a,e,b){var c=b.getCurrentBuyingOptionIndex(),d=function(b){var d=a.$(e.selector.iconfarm);if(d.length){var k=d[0].children;k.length&&(d=k[c],b!==g&&b.selectedRow!==g&&b.selectedRow.$row!==g&&a.$(b.selectedRow.$row)!==g&&(b=a.$(b.selectedRow.$row).index(),b!==c&&(k=k[b],d.style.display="none",k.style.display=
"block",c=b)))}};return{init:function(){a.on("a:pageUpdate",d);a.on("PageRefresh:ATF",d);a.on("a:accordion:buybox-accordion:select",d)}}})});
/* ******** */
(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("DetailPageBylineInfoAssets@core","DetailPageBylineInfo"):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
(function(r){var f=window.AmazonUIPageJS||window.P,p=f._namespace||f.attributeErrors,x=p?p("SocialShareWidgetAUI","AmazonUI"):f;x.guardFatal?x.guardFatal(r)(x,window):x.execute(function(){r(x,window)})})(function(r,f,p){var x="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(h){return typeof h}:function(h){return h&&"function"===typeof Symbol&&h.constructor===Symbol&&h!==Symbol.prototype?"symbol":typeof h};r.register("SocialShareWidget",function(){return function(h){function a(d){if(g[d])return g[d].exports;
var c=g[d]={i:d,l:!1,exports:{}};return h[d].call(c.exports,c,c.exports,a),c.l=!0,c.exports}var g={};return a.m=h,a.c=g,a.d=function(d,c,b){a.o(d,c)||Object.defineProperty(d,c,{enumerable:!0,get:b})},a.r=function(a){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})},a.t=function(d,c){if((1&c&&(d=a(d)),8&c)||4&c&&"object"==("undefined"===typeof d?"undefined":x(d))&&d&&d.__esModule)return d;var b=
Object.create(null);if(a.r(b),Object.defineProperty(b,"default",{enumerable:!0,value:d}),2&c&&"string"!=typeof d)for(var e in d)a.d(b,e,function(a){return d[a]}.bind(null,e));return b},a.n=function(d){var c=d&&d.__esModule?function(){return d.default}:function(){return d};return a.d(c,"a",c),c},a.o=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)},a.p="",a(a.s=6)}([function(h,a,g){Object.defineProperty(a,"__esModule",{value:!0});a.isSafari=a.isCSALoaded=a.isNativeAppShareAvailable=a.isNativeWebShareAvailable=
a.isMobileWeb=a.isMobileApp=a.isDesktop=a.isIOS=a.isAndroid=a.isIE=a.isAUILoaded=a.isUeAvailable=a.isClipboardAvailable=a.isRTL=a.isTwisterAsin=a.context=a.Device=void 0;var d,c=g(4);!function(a){a.Android="apan";a.IOS="apin";a.MWeb="mwn";a.Other="ud"}(d=a.Device||(a.Device={}));a.context=function(){var b=d.Other;(0,a.isMobileApp)()&&(0,a.isAndroid)()?b=d.Android:(0,a.isMobileApp)()&&(0,a.isIOS)()?b=d.IOS:(0,a.isMobileWeb)()&&(b=d.MWeb);var n="unknown";return(0,a.isMobileApp)()?n="mshop":(0,a.isMobileWeb)()?
n="mweb":(0,a.isDesktop)()&&(n="desktop"),{device:b,page:(0,a.isUeAvailable)()?f.ue_pty:"unknown",subPage:(0,a.isUeAvailable)()?f.ue_spty||f.ue_pti:"unknown",platform:n}};a.isTwisterAsin=function(){return!!f.isTwisterPage||!!f.twisterController||b};a.isRTL=function(){return"rtl"===document.dir};a.isClipboardAvailable=function(){return!!navigator.clipboard&&(0,c.isFunction)(navigator.clipboard.writeText)};a.isUeAvailable=function(){return!!f.ue};a.isAUILoaded=function(){var a;return(0,c.isString)(null===
(a=null===f||void 0===f?void 0:f.P)||void 0===a?void 0:a.AUI_BUILD_DATE)};a.isIE=function(){return(0,c.testUserAgent)(/MSIE|Trident/i)};a.isAndroid=function(){return(0,c.testUserAgent)(/android.([1-9]|[L-Z])/i)&&!(0,c.testUserAgent)(/trident|Edge/i)};a.isIOS=function(){return(0,c.testUserAgent)(/OS [1-9][0-9]*(_[0-9]*)+ like Mac OS X/i)&&!(0,c.testUserAgent)(/trident|Edge/i)};a.isDesktop=function(){return!((0,a.isAndroid)()||(0,a.isIOS)()||(0,a.isMobileApp)()||(0,a.isMobileWeb)())};a.isMobileApp=
function(){return/(Windowshop|Amazon|Amazon\.com)\//.test((0,c.getCookie)("amzn-app-id"))};a.isMobileWeb=function(){return 450>=f.screen.availWidth&&((0,c.testUserAgent)(/mobile|mini/i)||(0,a.isAndroid)()||(0,a.isIOS)())};a.isNativeWebShareAvailable=function(){return f.navigator&&(0,c.isFunction)(f.navigator.share)};a.isNativeAppShareAvailable=function(a){return a&&(0,c.isFunction)(a.share)};a.isCSALoaded=function(){return(0,c.isFunction)(f.csa)};a.isSafari=function(){var a;return/apple/i.test(null===
(a=f.navigator)||void 0===a?void 0:a.vendor)};var b=!1;(0,a.isAUILoaded)()&&f.P.when("mobile-inline-twister-critical").execute(function(){b=!0});a.default={context:a.context,isTwisterAsin:a.isTwisterAsin,isClipboardAvailable:a.isClipboardAvailable,isUeAvailable:a.isUeAvailable,isAUILoaded:a.isAUILoaded,isIE:a.isIE,isAndroid:a.isAndroid,isDesktop:a.isDesktop,isIOS:a.isIOS,isMobileApp:a.isMobileApp,isMobileWeb:a.isMobileWeb,isNativeWebShareAvailable:a.isNativeWebShareAvailable,isNativeAppShareAvailable:a.isNativeAppShareAvailable,
isCSALoaded:a.isCSALoaded,isSafari:a.isSafari,isRTL:a.isRTL}},function(h,a,g){Object.defineProperty(a,"__esModule",{value:!0});a.defaultCustomizeShareCSAData=a.defaultShareDataAttributes=a.REGEX_TO_REF_ID_AND_CHANNEL_APP=a.TRUE=a.FALSE=a.EMBED_CHANNEL_REF=a.CP_CHANNEL_REF=a.RAW_CHANNEL_PREFIX=a.EMPTY_STRING=a.DEFAULT_CSA_REF_ID=a.UNKNOWN=a.CSA_DEFAULT_VALUE=a.customize=a.CSA_HIT_TYPE=void 0;h=a.CSA_HIT_TYPE||(a.CSA_HIT_TYPE={});h.CLICK_SUCCESS="click_success";h.CLICK_ERROR="click_error";h.CLICK_CANCEL=
"click_cancel";h.SHARE="share";h.CUSTOMIZE_SHARE="click_customize_success";a.customize="customize";a.CSA_DEFAULT_VALUE={string:"unknown",number:0,boolean:2};a.UNKNOWN="unknown";a.DEFAULT_CSA_REF_ID="u_";a.EMPTY_STRING="";a.RAW_CHANNEL_PREFIX="raw:";a.CP_CHANNEL_REF="cp";a.EMBED_CHANNEL_REF="eb";a.FALSE="false";a.TRUE="true";a.REGEX_TO_REF_ID_AND_CHANNEL_APP={instagram:{refId:"in",channel:"Instagram"},snap:{refId:"sn",channel:"Snapchat"},discord:{refId:"di",channel:"Discord"},viber:{refId:"vi",channel:"Viber"},
telegram:{refId:"te",channel:"Telegram"},pinterest:{refId:"pi",channel:"Pinterest"},qzone:{refId:"qz",channel:"QQ Zone"},renren:{refId:"re",channel:"Renren"},twitter:{refId:"tw",channel:"Twitter"},airdrop:{refId:"ar",channel:"AirDrop"},tencentweibo:{refId:"tc",channel:"Tencent Weibo"},wechatmoment:{refId:"wm",channel:"WeChat Moment"},line:{refId:"li",channel:"Line"},whatsapp:{refId:"wa",channel:"Whatsapp"},weibo:{refId:"si",channel:"Sina Weibo"}};a.defaultShareDataAttributes={isInternal:a.CSA_DEFAULT_VALUE.boolean,
isRobot:a.CSA_DEFAULT_VALUE.boolean,userAgent:a.CSA_DEFAULT_VALUE.number,platform:a.CSA_DEFAULT_VALUE.string,ingress:a.CSA_DEFAULT_VALUE.string,asin:a.CSA_DEFAULT_VALUE.string,requestId:a.CSA_DEFAULT_VALUE.string,customerId:a.CSA_DEFAULT_VALUE.string,marketplaceId:a.CSA_DEFAULT_VALUE.string};a.defaultCustomizeShareCSAData={backgroundImagePhysicalId:a.EMPTY_STRING,deviceCoverImagePhysicalId:a.EMPTY_STRING,hasQuote:a.EMPTY_STRING,isCustomizedExperienceEnabled:a.EMPTY_STRING,isCustomized:a.EMPTY_STRING}},
function(h,a,g){Object.defineProperty(a,"__esModule",{value:!0});var d=g(3);h=function(){function a(b,e,n){this.REF_PARAM_NAME="ref_";a.isValid(b)||(b=a.getDefault());this.url=new URL(b);this._refMarker=new d.default(e,n)}return a.prototype.getUpdatedUrl=function(a){var b=new URL(this.raw);return b.searchParams.set(this.REF_PARAM_NAME,a),b.toString()},Object.defineProperty(a.prototype,"raw",{get:function(){return this.url.toString()},enumerable:!1,configurable:!0}),Object.defineProperty(a.prototype,
"refMarker",{get:function(){return this._refMarker},enumerable:!1,configurable:!0}),a.isValid=function(a){try{new URL(a)}catch(e){return!1}return!0},a.getDefault=function(){var a,e,n=null===(a=null===f||void 0===f?void 0:f.location)||void 0===a?void 0:a.href;if(!n)return(null===(e=null===f||void 0===f?void 0:f.ue)||void 0===e?0:e.sn)?"https://"+f.ue.sn:"https://amazon.com";a=new URL(n);e=a.searchParams.has("psc")?"?psc\x3d1":"";return f.ue_pti?f.location.origin+"/dp/"+f.ue_pti+e:(a.search=e,a.href)},
a.prototype.getReturnForChannel=function(a){a=this._refMarker.getReturnForChannel(a);return this.getUpdatedUrl(a)},a.prototype.getClickForChannel=function(a){a=this._refMarker.getClickForChannel(a);return this.getUpdatedUrl(a)},Object.defineProperty(a.prototype,"return",{get:function(){return this.getUpdatedUrl(this._refMarker.return)},enumerable:!1,configurable:!0}),Object.defineProperty(a.prototype,"click",{get:function(){return this.getUpdatedUrl(this._refMarker.click)},enumerable:!1,configurable:!0}),
a}();a.default=h},function(h,a,g){Object.defineProperty(a,"__esModule",{value:!0});var d,c=g(0),b=g(1);!function(a){a.RETURN="r";a.CLICK="cl"}(d||(d={}));h=function(){function a(a,d){if(void 0===a&&(a="ur"),void 0===d&&(d=void 0),this.PREFIX="cm_sw",this.id="",this.refId="",this.cxt={device:c.Device.Other,page:"",subPage:"",platform:b.UNKNOWN},2>a.length)throw new TypeError("refId must be 2 or more characters long");this.refId=a;this.cxt=(0,c.context)();this.treatment=d;this.generateUniqueId()}return Object.defineProperty(a.prototype,
"return",{get:function(){return this.get(d.RETURN)},enumerable:!1,configurable:!0}),Object.defineProperty(a.prototype,"click",{get:function(){return this.get(d.CLICK)},enumerable:!1,configurable:!0}),a.prototype.getReturnForChannel=function(a){return this.PREFIX+"_"+d.RETURN+"_"+a+"_"+this.cxt.device+"_"+this.refId+"_"+(this.treatment?this.treatment+"_":"")+this.id},a.prototype.getClickForChannel=function(a){return this.PREFIX+"_"+d.CLICK+"_"+a+"_"+this.cxt.device+"_"+this.refId+"_"+this.id},a.prototype.generateUniqueId=
function(){var a,b=null===(a=null===f||void 0===f?void 0:f.ue)||void 0===a?void 0:a.rid;return b||(b=(""+Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2)).substring(0,13)),this.id=b},a.prototype.get=function(a){return this.PREFIX+"_"+a+"_"+this.cxt.device+"_"+this.refId+"_"+(this.treatment?this.treatment+"_":"")+this.id},a}();a.default=h},function(h,a,g){Object.defineProperty(a,"__esModule",{value:!0});a.getDPXObject=a.getCookie=a.testUserAgent=a.truncate=a.isString=a.isEmpty=
a.isNumber=a.isFunction=void 0;a.isFunction=function(a){return"function"==typeof a};a.isNumber=function(a){return!isNaN(a)&&"number"==typeof a};a.isEmpty=function(a){return!a||!a.length};a.isString=function(a){return"string"==typeof a};a.truncate=function(a,c){void 0===a&&(a="");var b=Array(3).fill(".");return a.length>c?a.substring(0,c-3)+b.join(""):a};a.testUserAgent=function(a){if(!f&&!f.navigator)return!1;try{return a.test(f.navigator.userAgent)}catch(c){return!1}};a.getCookie=function(a){a+=
"\x3d";for(var d=document.cookie.split(";"),b=0;b<d.length;b++){for(var e=d[b];" "==e.charAt(0);)e=e.substring(1);if(0==e.indexOf(a))return e.substring(a.length,e.length)}return""};a.getDPXObject=function(){var a,c;return null===(c=null===(a=f.DetailPage)||void 0===a?void 0:a.StateController)||void 0===c?void 0:c.state};a.default={isFunction:a.isFunction,isNumber:a.isNumber,isEmpty:a.isEmpty,isString:a.isString,truncate:a.truncate,testUserAgent:a.testUserAgent,getCookie:a.getCookie,getDPXObject:a.getDPXObject}},
function(h,a,g){Object.defineProperty(a,"__esModule",{value:!0});var d=g(0),c=g(9),b=g(1);h=function(){function a(){}return a.logCounter=function(a,b){(0,d.isUeAvailable)()&&(a=this.BASE_METRIC_NAME+"."+a+(b?"."+b:""),f.ue.count(a,(f.ue.count(a)||0)+1))},a.logCounterRefactor=function(a,b){(0,d.isUeAvailable)()&&(b=b?"."+b.toLowerCase():"",a=""+this.BASE_METRIC_NAME+b+"."+this.platform+this.metricName+"."+a.toLowerCase(),f.ue.count(a,(f.ue.count(a)||0)+1))},a.logLoad=function(a){(0,d.isUeAvailable)()&&
(a=this.BASE_METRIC_NAME+"."+this.platform+this.metricName+"."+a.toLowerCase(),f.ue.count(a,(f.ue.count(a)||0)+1))},a.logFatal=function(a){(0,d.isAUILoaded)()&&f.P.log(a,"FATAL",this.BASE_METRIC_NAME)},a.logCSAEvent=function(a,b){(0,d.isCSALoaded)()&&(new c.default).withCSAClickEventData(b).withShareHitType(a).logEvent()},a.startTimer=function(a){f.uet&&(0,d.isUeAvailable)()&&(f.uet("bb",this.BASE_METRIC_NAME,{wb:1}),f.uet("bb",this.BASE_METRIC_NAME+"."+a,{wb:1}))},a.stopTimer=function(a){f.uet&&
(0,d.isUeAvailable)()&&(f.uet("be",this.BASE_METRIC_NAME,{wb:1}),f.uet("be",this.BASE_METRIC_NAME+"."+a,{wb:1}));f.uex&&(0,d.isUeAvailable)()&&(f.uex("ld",this.BASE_METRIC_NAME,{wb:1}),f.uex("ld",this.BASE_METRIC_NAME+"."+a,{wb:1}))},a.BASE_METRIC_NAME="SocialShareFramework",a.platform=b.UNKNOWN,a.metricName="",a.getMetricName=function(b,e){var n;if(void 0===e&&(e=""),(0,d.isUeAvailable)()){var c=(0,d.context)();a.platform=c.platform;a.metricName=e?"."+e.toLowerCase():""}return(b=b('[data-action\x3d"ssf-share-icon"]').data())?
(b=(null===(n=b.ssfShareIcon)||void 0===n?void 0:n.shareDataAttributes)||{},n=b.ingress,b=b.platform,((void 0===n?"unknown":n)+"."+(void 0===b?"unknown":b)+(e?"."+e:"")).toLowerCase()):""},a}();a.default=h},function(h,a,g){Object.defineProperty(a,"__esModule",{value:!0});a.SocialShareCore=void 0;h=g(7);var d=g(2),c=g(8),b=g(5),e=g(10),n=g(3),f=g(0);g=g(1);a.SocialShareCore={Channels:h.default,Url:d.default,Translations:c.default,Metrics:b.default,ShareSheet:e.default,RefMarker:n.default,Detection:f.default,
Constants:g};a.default=a.SocialShareCore},function(h,a,g){Object.defineProperty(a,"__esModule",{value:!0});a.default=function(a,c){var b={email:{label:"Email",name:"email",ref:"em",shareBaseUrl:"mailto:",image:"https://m.media-amazon.com/images/G/01/share-icons/email-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/email-squared.svg",canOpenInPopup:!1,getSharingUrl:function(b){var e="?subject\x3d"+encodeURIComponent(a.emailSubject||a.title),n="\x26body\x3d"+encodeURIComponent(a.title);
b=encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref));return""+this.shareBaseUrl+e+n+" "+b}},pi:{label:"Pinterest",name:"pinterest",ref:"pi",shareBaseUrl:"https://www.pinterest.com/pin/create/button/",image:"https://m.media-amazon.com/images/G/01/share-icons/pinterest-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/pinterest-squared.svg",canOpenInPopup:!0,getSharingUrl:function(b){b="?url\x3d"+encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref));
var e="\x26description\x3d"+encodeURIComponent(a.title),n="\x26media\x3d"+encodeURIComponent(a.image);return""+this.shareBaseUrl+b+e+n+"\x26method\x3dbutton"}},li:{label:"Line",name:"line",ref:"li",shareBaseUrl:"https://social-plugins.line.me/lineit/share",image:"https://m.media-amazon.com/images/G/01/share-icons/line-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/line-squared.svg",canOpenInPopup:!0,getSharingUrl:function(b){var e="?text\x3d"+encodeURIComponent(a.text)+
" "+encodeURIComponent(a.title);b="\x26url\x3d"+encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref));return""+this.shareBaseUrl+e+b}},fb:{label:"Facebook",name:"facebook",ref:"fa",shareBaseUrl:"https://www.facebook.com/dialog/share",image:"https://m.media-amazon.com/images/G/01/share-icons/facebook-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/facebook-squared.svg",canOpenInPopup:!0,getSharingUrl:function(b){b=["?_encoding\x3dUTF8\x26app_id\x3d465632727431967\x26display\x3dpopup",
"href\x3d"+encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref)),"redirect_uri\x3d"+encodeURIComponent(a.shareUrl.getReturnForChannel(this.ref).replace("_r_","_s_")),"hashtag\x3d"+encodeURIComponent("#"+(a.hashtags[0]||"Amazon"))].join("\x26");return""+this.shareBaseUrl+b}},tw:{label:"Twitter",name:"twitter",ref:"tw",shareBaseUrl:"https://twitter.com/intent/tweet",image:"https://m.media-amazon.com/images/G/01/share-icons/twitter-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/twitter-squared.svg",
canOpenInPopup:!0,getSharingUrl:function(b){var e="?text\x3d"+encodeURIComponent(a.title);b="\x26url\x3d"+encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref));var n="\x26hashtags\x3d"+a.hashtags.join(","),c="\x26via\x3d"+encodeURIComponent("Amazon");return""+this.shareBaseUrl+e+b+n+c}},wa:{label:"WhatsApp",name:"whatsapp",ref:"wa",shareBaseUrl:"https://api.whatsapp.com/send?text\x3d",image:"https://m.media-amazon.com/images/G/01/share-icons/whatsapp-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/whatsapp-squared.svg",
canOpenInPopup:!0,getSharingUrl:function(b){b="\n              "+encodeURIComponent(a.title)+"\n              "+encodeURIComponent(a.text)+"\n              "+encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref));return""+this.shareBaseUrl+b}},sms:{label:"SMS",name:"sms",ref:"sms",shareBaseUrl:"sms:",image:"https://m.media-amazon.com/images/G/01/share-icons/sms-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/sms-squared.svg",canOpenInPopup:!1,getSharingUrl:function(b){b=
"\n              "+encodeURIComponent(a.title)+"\n              "+encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref));return""+this.shareBaseUrl+b}},embed:{label:"Embed",name:"embed",ref:"eb",shareBaseUrl:"",image:"https://m.media-amazon.com/images/G/01/share-icons/embed-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/embed-squared.svg",canOpenInPopup:!1,getSharingUrl:function(){return""}},copy:{label:"Copy",name:"copy",ref:"cp",shareBaseUrl:"",image:"https://m.media-amazon.com/images/G/01/share-icons/link-circular.svg",
imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/link-squared.svg",canOpenInPopup:!1,getSharingUrl:function(){return""}}};if(null==c?0:c.length){var e={};return c.forEach(function(a){b[a]&&(e[a]=b[a])}),e}return b}},function(h,a,g){Object.defineProperty(a,"__esModule",{value:!0});a.default={}},function(h,a,g){Object.defineProperty(a,"__esModule",{value:!0});var d=g(0),c=g(1);h=function(){function a(){var b=this;this.generateTimestampCollection=function(){var a=(new Date).getTimezoneOffset();
a=b.getDateTimeByOffset(a);var e=b.getDateTimeByOffset(0);return{hitDay:a.split("T")[0],hitDatetime:a,hitDatetimeUtc:e}};this.getMarketplaceId=function(a){return"string"==typeof a?a:f.ue&&f.ue.mid?f.ue.mid:c.CSA_DEFAULT_VALUE.string};var d=this.generateTimestampCollection();this.csaMetricsData={schemaId:a.CSA_SCHEMA_ID,userAgentId:c.CSA_DEFAULT_VALUE.number,hitDay:d.hitDay,hitDatetime:d.hitDatetime,hitDatetimeUtc:d.hitDatetimeUtc,pageType:f.ue_pty?f.ue_pty:c.CSA_DEFAULT_VALUE.string,subPageType:f.ue_spty?
f.ue_spty:c.CSA_DEFAULT_VALUE.string,sessionId:f.ue&&f.ue.sid?f.ue.sid:c.CSA_DEFAULT_VALUE.string}}return a.prototype.withCSAClickEventData=function(a){var b=a.shareDataAttributes;if(this.csaMetricsData.customerId=b.customerId?b.customerId:c.CSA_DEFAULT_VALUE.string,this.csaMetricsData.httpRequestId=b.requestId?b.requestId:c.CSA_DEFAULT_VALUE.string,this.csaMetricsData.asin=b.asin?b.asin:c.CSA_DEFAULT_VALUE.string,this.csaMetricsData.ingress=b.ingress?b.ingress:c.CSA_DEFAULT_VALUE.string,this.csaMetricsData.platform=
b.platform?b.platform:c.CSA_DEFAULT_VALUE.string,this.csaMetricsData.isInternal=this.getCSANumberMapping(b.isInternal),this.csaMetricsData.isRobot=this.getCSANumberMapping(b.isRobot),this.csaMetricsData.channel=a.channel?a.channel:c.CSA_DEFAULT_VALUE.string,this.csaMetricsData.refMarker=a.refMarker?a.refMarker:c.CSA_DEFAULT_VALUE.string,this.csaMetricsData.referrerUrl=a.refererURL?a.refererURL:c.CSA_DEFAULT_VALUE.string,this.csaMetricsData.marketplaceId=this.getMarketplaceId(b.marketplaceId),this.csaMetricsData.isExperiment=
/T\d+/.test(a.treatment)?"Y":"N",a.weblab)b=this.csaMetricsData.shareEntities,(b=void 0===b?{}:b)[a.weblab]=a.treatment,this.csaMetricsData.shareEntities=b;a.customizeShareCSAData&&(b=this.csaMetricsData.shareEntities,b=void 0===b?{}:b,a.customizeShareCSAData.isCustomizedExperienceEnabled===c.TRUE&&(b.backgroundImagePhysicalId=a.customizeShareCSAData.backgroundImagePhysicalId,b.deviceCoverImagePhysicalId=a.customizeShareCSAData.deviceCoverImagePhysicalId,b.hasQuote=a.customizeShareCSAData.hasQuote,
b.isCustomized=a.customizeShareCSAData.isCustomized,this.csaMetricsData.shareEntities=b));return this},a.prototype.withShareHitType=function(a){return this.csaMetricsData.shareHitType=a||c.CSA_DEFAULT_VALUE.string,this},a.prototype.getCSANumberMapping=function(a){return isNaN(Number(a))?2:Number(a)},a.prototype.getDateTimeByOffset=function(b){var c=new Date;0!==b&&(b*=a.MINUTES_TO_MILISECONDS,c=c.getTime()-b,c=new Date(c));return c.toISOString().split("Z")[0].split(".")[0]},a.prototype.logEvent=function(){(0,
d.isCSALoaded)()&&f.csa(a.CSAPluginId,{producerId:a.CSA_PRODUCER_ID})(a.CSA_LOG_EVENT,this.csaMetricsData)},a.MINUTES_TO_MILISECONDS=6E4,a.CSAPluginId="Events",a.CUSTOMIZE_SHARE_ENTITY_NAME="CustomizeShare",a.CSA_PRODUCER_ID="social-share",a.CSA_LOG_EVENT="log",a.CSA_SCHEMA_ID="SocialShareCSACustomEvent.CSAShareMetrics.8",a}();a.default=h},function(h,a,g){var d=this&&this.__assign||function(){return(d=Object.assign||function(a){for(var b,c=1,d=arguments.length;c<d;c++)for(var e in b=arguments[c])Object.prototype.hasOwnProperty.call(b,
e)&&(a[e]=b[e]);return a}).apply(this,arguments)};Object.defineProperty(a,"__esModule",{value:!0});var c,b=g(5),e=g(0),n=g(2),m=g(4),l=g(1);(0,e.isAUILoaded)()&&f.P.when("mash").execute(function(a){return c=a});h=function(){function a(a){this.sheetOptions={title:l.EMPTY_STRING,text:l.EMPTY_STRING,shareUrl:new n.default("http://amazon.com/","ur"),lang:"en",shareDataAttributes:l.defaultShareDataAttributes,refererURL:"",image:"",customizeShareCSAData:l.defaultCustomizeShareCSAData};this.sheetOptions=
d(d({},this.sheetOptions),a);this.shareUrl=a.shareUrl}return a.prototype.launchNativeWeb=function(){var a,c=this,e=this.sheetOptions.shareDataAttributes.ingress,d={channel:l.EMPTY_STRING,refMarker:this.shareUrl.refMarker.click,refererURL:this.sheetOptions.refererURL,shareDataAttributes:this.sheetOptions.shareDataAttributes,customizeShareCSAData:this.sheetOptions.customizeShareCSAData},g=this.shareUrl.return;this.sheetOptions.tinyUrl&&(g=this.sheetOptions.tinyUrl,b.default.logCounter("MWeb.Tiny.Success"),
b.default.logCounterRefactor("Tiny.Success",e));var h=(0,m.isFunction)(this.sheetOptions.sheetShownCallback);try{null===(a=null===f||void 0===f?void 0:f.navigator)||void 0===a||a.share({url:g,title:this.sheetOptions.title,text:this.sheetOptions.text}).then(function(){h&&c.sheetOptions.sheetShownCallback();b.default.logCSAEvent(l.CSA_HIT_TYPE.CLICK_SUCCESS,d);b.default.logCSAEvent(l.CSA_HIT_TYPE.SHARE,d)}).catch(function(){h&&c.sheetOptions.sheetShownCallback();b.default.logCSAEvent(l.CSA_HIT_TYPE.CLICK_SUCCESS,
d);b.default.logCSAEvent(l.CSA_HIT_TYPE.CLICK_CANCEL,d)})}catch(B){b.default.logCSAEvent(l.CSA_HIT_TYPE.CLICK_ERROR,d)}},a.prototype.launchNativeApp=function(){var a=this,e=this.shareUrl.refMarker.click,g=this.sheetOptions.shareDataAttributes,h=this.sheetOptions.refererURL,f=this.sheetOptions.customizeShareCSAData,n=this.sheetOptions.shareDataAttributes.ingress,p=l.EMPTY_STRING,A=this.shareUrl.return;this.sheetOptions.tinyUrl&&(A=this.sheetOptions.tinyUrl,b.default.logCounter("MShop.Tiny.Success"),
b.default.logCounterRefactor("Tiny.Success",n));var v={channel:p,refMarker:e,refererURL:h,shareDataAttributes:g,customizeShareCSAData:f};e={messagePlain:this.getShareMessage,messagePlain160:this.getShare160Message,messagePlain140:this.getShare140Message,messageHTML:this.getShareMessage,url:A,imageURL:this.sheetOptions.image,subject:this.sheetOptions.text};null==c||c.share(d(d({},e),{successCallback:function(){(0,m.isFunction)(a.sheetOptions.sheetShownCallback)&&a.sheetOptions.sheetShownCallback();
b.default.logCSAEvent(l.CSA_HIT_TYPE.CLICK_SUCCESS,v)},failCallback:function(){b.default.logCSAEvent(l.CSA_HIT_TYPE.CLICK_ERROR,v)},shareServiceSelectedCallback:function(c){c&&"'null'"!==c?((0,m.isFunction)(a.sheetOptions.channelSelectCB)&&a.sheetOptions.channelSelectCB(c),v.channel=a.getChannelByKeyword(c).channel,c=a.getChannelByKeyword(c).refId,v.refMarker=a.shareUrl.refMarker.getClickForChannel(c),b.default.logCSAEvent(l.CSA_HIT_TYPE.SHARE,v)):b.default.logCSAEvent(l.CSA_HIT_TYPE.CLICK_CANCEL,
v)}}))},a.prototype.launch=function(a){(0,e.isNativeAppShareAvailable)(c)?this.launchNativeApp():(0,e.isNativeWebShareAvailable)()?this.launchNativeWeb():(0,m.isFunction)(a)?a():(b.default.logCounter("Click.ShareUnavailable"),b.default.logCounterRefactor("Click.ShareUnavailable",this.sheetOptions.shareDataAttributes.ingress))},Object.defineProperty(a.prototype,"getShare160Message",{get:function(){var a=this.sheetOptions.tinyUrl||this.shareUrl.return,b=a.length+2;return(0,m.truncate)(this.sheetOptions.title,
160-b)+" "+a},enumerable:!1,configurable:!0}),Object.defineProperty(a.prototype,"getShare140Message",{get:function(){var a=this.sheetOptions.tinyUrl||this.shareUrl.return,b=a.length+2;return(0,m.truncate)(this.sheetOptions.title,140-b)+" "+a},enumerable:!1,configurable:!0}),a.prototype.getRefByRegex=function(a){return l.REGEX_TO_REF_ID_AND_CHANNEL_APP[a].refId},a.prototype.getChannelByRegex=function(a){return l.REGEX_TO_REF_ID_AND_CHANNEL_APP[a].channel},a.prototype.getChannelByKeyword=function(a){var b=
l.RAW_CHANNEL_PREFIX+a,c=l.DEFAULT_CSA_REF_ID,e=a.match(/instagram|snap|discord|viber|telegram|pinterest|qzone|renren|twitter|airdrop|tencentweibo|wechatmoment|line|whatsapp|weibo/ig);if(e&&e.length)return{channel:this.getChannelByRegex(e[0].toLowerCase()),refId:this.getRefByRegex(e[0].toLowerCase())};switch(!0){case /android.messaging|sms|android.apps.messaging|mms/gi.test(a):b="SMS";c="sm";break;case /outlook|mail/gi.test(a):b="Email";c="em";break;case /clipboardactivity|copy/gi.test(a):b="Copy";
c="cp";break;case /facebook.composer/gi.test(a):b="Facebook";c="fb";break;case /facebook.messenger|FacebookMessenger/gi.test(a):b="FacebookMessenger";c="fm";break;case /tencent|wechat/gi.test(a):b="WeChat";c="we";break;case /unknown|null/gi.test(a):b="unknown",c="u"}return{channel:b,refId:c}},Object.defineProperty(a.prototype,"getShareMessage",{get:function(){return this.sheetOptions.title+" "+(this.sheetOptions.tinyUrl||this.shareUrl.return)},enumerable:!1,configurable:!0}),a}();a.default=h}])});
"use strict";r.register("SocialShareWidgetConfig",function(){var h=Object.freeze({MODAL:"modal",POPOVER:"popover",EASYMODE:"easymode"}),a=Object.freeze({IOS:"ios",ANDROID:"android",VARIABLE:"variable"});return{WIDGET_TYPE:h,WIDGET_ICON:a,excludedChannels:["sms","wa"],lineMarketplaces:["A1VC38T7YXB528"],cnMarketplace:["AAHKV2X7AFYLW"],nonCNChannels:["fb","tw","pi"],defaultShareData:{url:"",title:"Amazon.com",text:"Check this out!",image:"",hashtags:["Amazon"],type:h.POPOVER,lang:"en",refId:"ts",channels:[],
refererURL:"",treatment:"",weblab:"",customize:!1,caf:!1,cafSwitch:!1,t:{},associateLink:{},popoverPosition:"triggerBottom"},defaultWidgetData:{icon:a.VARIABLE,background:!0,width:24},shareDataAttributes:{isInternal:2,isRobot:2,userAgent:f.navigator.userAgent,platform:"DESKTOP",ingress:f.ue_pty,asin:f.ue_pti,requestId:f.ue_id,customerId:f.opts&&f.opts.customerId,marketplaceId:f.ue_mid},iconMap:{ios:"https://m.media-amazon.com/images/G/01/share-icons/share-std.svg",android:"https://m.media-amazon.com/images/G/01/share-icons/share-android.svg"}}});
"use strict";r.when("A","SocialShareWidget","SocialShareWidgetTemplating","SocialShareWidgetConfig").register("SocialShareWidgetAUI",function(h,a,g,d){var c=a.SocialShareCore,b=c.Metrics,e=0,n=function(){},m=!1,l=b.getMetricName(h.$),w=h.constants.HIDE_CLASS;b.startTimer(l);b.logCounter("DPX.Desktop.ImageBlockRender");try{(function(){var a=h.$,u=c.Detection,y=c.Translations,t=c.Channels,C=c.ShareSheet,U=c.Url,B=c.Constants,A=function(a){a=a.data("share")||a.find("[data-share]").data("share");return h.extend({},
d.defaultWidgetData,a)},v=a(".ssf-share-trigger"),k=d.defaultShareData,D=A(v),V=k.url,O=a("#ac-getlink-bottomsheet"),I=a('[data-action\x3d"ssf-share-icon"]'),G=function(){var a=d.iconMap;return u.isDesktop()?a.ios:D.icon===d.WIDGET_ICON.VARIABLE?u.isIOS()?a.ios:a.android:a[D.icon]},R=function(a){a.find('[class*\x3d"ssf-multi-"]').length||a.find(".ssf-share-trigger").addClass("ssf-multi-"+Math.random().toString(36).slice(2));v=a.find('[class*\x3d"ssf-multi-"]')},H=void 0,z=void 0,q=void 0,E=void 0,
J=void 0,W=void 0,N=void 0;r.when("a-sheet").execute(function(a){return H=a});r.when("a-popover").execute(function(a){return z=a});r.when("a-modal").execute(function(a){return q=a});r.when("SocialShareWidgetTiny").execute(function(a){return N=a});var X=function(a,b){var c=2<arguments.length&&arguments[2]!==p?arguments[2]:"ssf-share-bottom-sheet",e=k.customize||k.caf;if(!E||e)E=H.create({name:c,inlineContent:a,closeType:"icon",height:b});H.showSheet(E)},S=function(a){var b=a.type===d.WIDGET_TYPE.POPOVER&&
z,c=a.type===d.WIDGET_TYPE.MODAL&&q,e=a.type===d.WIDGET_TYPE.EASYMODE&&z;a=g.build(a);H?X(a.getBottom()):b?(b=a.getPopover(),v.hasClass("a-declarative")||(J=z.create(v,{name:"ssf-share-popover",position:k.popoverPosition,inlineContent:b,activate:"onclick",closeButton:!1,width:160,padding:"none",popoverLabel:"Share Popup",closeButtonLabel:"Close Share Popup"}).show())):c?(b=a.getModal(),v.hasClass("a-declarative")||(W=q.create(v,{inlineContent:b,width:600}).show())):e&&(b=a.getEasyModeContent(),e=
z.get("easy-mode-menu").getContent(),c=e.find("#emShare"),e=e.find("#SocialShare"),0<e.length&&e[0].remove(),c[0].innerHTML+=b)},Z=function(a){if(a.customize||a.caf)b.logCounter("webview.sharesheet.caf.background"),b.logCounterRefactor("webview.sharesheet.caf.background",a.shareDataAttributes.ingress),r.when("mash").execute(function(a){a.addEventListener("appPause",L)})},M=function(a){r.when("SocialShareWidgetCustomize").execute(function(b){var c=g.build(a);X(c.getCustomize(),650,"ssf-customize-bottom-sheet");
b.init(a,S,L);Z(a)})},L=function Y(){r.when("mash").execute(function(a){a.removeEventListener("appPause",Y)});J&&z.get(v).hide();E&&H.hideSheet(E);W&&q.get(v).hide()},aa=function(){var a=k.shareDataAttributes.asin,b=f.DetailPage;if(!b)return!1;b=b.StateController&&b.StateController.getState().current_asin;k.shareDataAttributes.asin="string"==typeof b?b:a;return a!==b},T=function(a){a.addClass("ssf-noclick");a.find(".a-spinner").removeClass(w);a.find("i").hide()},P=function(a){a.removeClass("ssf-noclick");
a.find(".a-spinner").addClass(w);a.find("i").show()},x=function(c){var e=c.shareData,q=c.copyElement,d=e.shareDataAttributes,g=e.t,f=e.treatment;f=f===p?"":f;var k=e.weblab;k=k===p?"":k;c={channel:"copy",refMarker:e.shareUrl.refMarker.getClickForChannel(c.channelRef),shareDataAttributes:d,treatment:f,weblab:k};b.logCSAEvent(B.CSA_HIT_TYPE.SHARE,c);b.logCounter("DPX.Desktop.CopySuccess");b.logCounter(l,"CopySuccess");b.logCounterRefactor("CopySuccess",d.ingress);u.isDesktop()?function(){var a=q.find(".copy-label");
a.text(g.taf_copy_url_changeover);h.delay(function(){L();a.text(g.taf_copy_name)},1E3)}():(a(".ssf-feedback").show(),L())},F=function(a){b.logCSAEvent(B.CSA_HIT_TYPE.CLICK_ERROR,a);b.logCounter("DPX.Desktop.CopyFailure");b.logCounter(l,"CopyFailure");b.logCounterRefactor("CopyFailure",k.shareDataAttributes.ingress)},Q=function(a){var b=a.shareData;a=a.channelRef;var c=b.shareUrl,q=b.socialLinks;q=q===p?{}:q;a=a?c.getReturnForChannel(a):c.return;return{csrfToken:b.csrfToken,gcmToken:b.gcmToken,url:a,
originalUrl:q.shareframework||b.url||a,refMarkerId:e++}};a(document).delegate(".ssf-channel:not(.copy,.embed)","click",function(c){c.preventDefault();c.stopPropagation();b.logCounter("DPX.Desktop.ChannelClick");b.logCounter(l,"ChannelClick");b.logCounterRefactor("ChannelClick",k.shareDataAttributes.ingress);var e=a(this),q=e.data("key"),d=k;c=d.refererURL;var g=d.shareDataAttributes,m=d.treatment;m=m===p?"":m;var E=d.weblab;E=E===p?"":E;var n=d.builtChannels[q],M=n.ref;q=d.shareUrl.refMarker.getClickForChannel(M);
d=n.name;var J=n.getSharingUrl();b.logCSAEvent(B.CSA_HIT_TYPE.SHARE,{channel:d,refMarker:q,refererURL:c,shareDataAttributes:g,treatment:m,weblab:E});c=Q({shareData:k,channelRef:M});T(e);N.fetch({data:c,callback:function(a){P(e);a&&(J=n.getSharingUrl(a),b.logCounter("Desktop.Tiny.Success"),b.logCounterRefactor("Tiny.Success",g.ingress));if("em"===M)f.open(J,"_self");else if(u.isDesktop()){a=screen.width;var c=screen.height,q="pi"===M?900:600,d=Math.min(q,.7*a);q=Math.min(q,.7*c);f.open(J,"_blank",
"toolbar\x3d0,status\x3d0,width\x3d"+d+",height\x3d"+q+",top\x3d"+(c/2-q/2)+",left\x3d"+(a/2-d/2))}else f.open(J,"_blank");L();h.trigger("ssf:event:share",k)}})});h.declarative("ssf-share-icon","click",function(c){b.logCounter("DPX.Desktop.SheetClick");b.logCounter(l,"SheetClick");if(m)return L();R(c.$currentTarget);k=h.extend(k,c.data);k.shareDataAttributes=h.extend(d.shareDataAttributes,c.data.shareDataAttributes);var e=k.shareDataAttributes.ingress;b.logCounterRefactor("SheetClick",e);if(!h.objectIsEmpty(c.data.associateLink)&&
O.length)b.logCounter("ShareIngress.GetLink.T1"),b.logCounterRefactor("ShareIngress.GetLink.T1",e),h.trigger("ac-getlink-bottomsheet-event",k);else{h.extend(y[k.lang],k.t);var q=t(k,k.channels);k.builtChannels=q;k.url=k.url.startsWith("/")?""+f.location.origin+k.url:k.url;k.shareUrl=new U(k.url,k.refId);aa()&&(k.shareUrl=new U(k.url,k.refId),k.shareUrl.url.searchParams.set("psc",1));u.isDesktop()?(k.image=k.image||a("#imgTagWrapperId img").attr("src"),S(k),b.logCounter("DPX.Desktop.SheetOpen"),b.logCounter(l,
"SheetOpen"),b.logCounterRefactor("SheetOpen",e),b.logCSAEvent(B.CSA_HIT_TYPE.CLICK_SUCCESS,{channel:B.EMPTY_STRING,refMarker:k.shareUrl.refMarker.click,refererURL:k.refererURL,shareDataAttributes:k.shareDataAttributes,treatment:k.treatment||"",weblab:k.weblab||""})):k.customize||k.caf?M(k):(T(c.$currentTarget),q=Q({shareData:k}),k=h.extend(k,{sheetShownCallback:function(){P(c.$currentTarget)}}),N.fetch({data:q,callback:function(a){k.tinyUrl=a;(new C(k)).launch(function(){S(k);b.logCounter("DPX.Desktop.SheetOpen");
b.logCounter(l,"SheetOpen");b.logCounterRefactor("SheetOpen",e);P(c.$currentTarget)})}}));u.isSafari()&&u.isDesktop()&&(q=Q({shareData:k,channelRef:B.CP_CHANNEL_REF}),N.fetch({data:q,callback:function(a){b.logCounter("DPX.Desktop.TinyUrlOnSheetOpen");b.logCounter(l,"TinyUrlOnSheetOpen");b.logCounterRefactor("TinyUrlOnSheetOpen",e);V=a}}));h.trigger("ssf:event:sheetOpen",k)}});a(document).delegate(".ssf-copy,.ssf-channel.copy","click",function(c){b.logCounter("DPX.Desktop.ChannelClick");b.logCounter(l,
"ChannelClick");b.logCounterRefactor("ChannelClick",k.shareDataAttributes.ingress);c.preventDefault();var e=a(this),q=B.CP_CHANNEL_REF,d=k.shareUrl.getReturnForChannel(q);u.isSafari()&&u.isDesktop()?navigator.clipboard.writeText(V||d).then(function(){x({shareData:k,copyElement:e,channelRef:q})},function(){F(csaOptions)}):(c=Q({shareData:k,channelRef:B.CP_CHANNEL_REF}),T(e),N.fetch({data:c,callback:function(a){P(e);navigator.clipboard.writeText(a||d).then(function(){x({shareData:k,copyElement:e,channelRef:q})},
function(){F(csaOptions)})}}));h.trigger("ssf:event:share",k)});a(document).delegate(".ssf-embed,.ssf-channel.embed","click",function(c){c.preventDefault();var e=k;c=e.shareDataAttributes;var d=e.treatment;d=d===p?"":d;var g=e.weblab;g=g===p?"":g;e={channel:"embed",refMarker:e.shareUrl.refMarker.getClickForChannel(B.EMBED_CHANNEL_REF),shareDataAttributes:c,treatment:d,weblab:g};b.logCSAEvent(B.CSA_HIT_TYPE.SHARE,e);b.logCounter("DPX.Desktop.ChannelClick");b.logCounter(l,"ChannelClick");b.logCounterRefactor("ChannelClick",
c.ingress);q.create(a(".ssf-channel.embed"),k.kpModalParams).show()});n=function(){v=a(".ssf-share-trigger");D=A(v);var b=D.width;if(!a(".ssf-background").length&&D.background){var c=1.4*b;c=a('\x3cdiv class\x3d"ssf-background'+(D.floatedIcon?"-float":"")+'"\x3e\x3c/div\x3e').css({width:c,height:c});v.wrap(c)}D.icon&&v.css({height:b,width:b,backgroundImage:"url("+G()+")"})};u.isIE()&&a(".ssf-share-trigger,.ssf-background").remove();h.on("a:popover:afterUpdatePosition:ssf-share-popover",function(a){a=
a.popover.$popover;var b=a.position().left-48;a.find(".a-arrow-border").css({right:24,left:""});a.css({left:b})});h.on("ssf:event:trigger-share-widget",function(a){h.trigger("a:declarative:ssf-share-icon:click",{data:a,$currentTarget:(1<arguments.length&&arguments[1]!==p?arguments[1]:p)||I})});h.on("a:popover:show:ssf-share-popover",function(){return m=!0});h.on("a:popover:hide:ssf-share-popover",function(){return m=!1});h.on("a:sheet:beforeShow:ssf-customize-bottom-sheet",function(b){b.sheet.$container.css("height",
"");r.when("a-switch").execute(function(b){k.caf&&b.getSwitch(a(".ssf-caf-toggle")).isOn(!!k.cafSwitch)})});n()})()}catch(K){b.logCounter("DPX.Desktop.Error"),b.logCounter(l,"Error"),b.logLoad("Error"),b.logFatal("Error loading Share Framework AUI: "+K.toString())}finally{b.logCounter("DPX.Desktop.Render"),b.logCounter(l,"Render"),b.logLoad("Render"),h.trigger("ssf:event:load"),b.stopTimer(l)}return{init:n}});"use strict";var F=function(){return function(h,a){if(Array.isArray(h))return h;if(Symbol.iterator in
Object(h)){var g=[],d=!0,c=!1,b=p;try{for(var e=h[Symbol.iterator](),f;!(d=(f=e.next()).done)&&(g.push(f.value),!a||g.length!==a);d=!0);}catch(m){c=!0,b=m}finally{try{if(!d&&e["return"])e["return"]()}finally{if(c)throw b;}}return g}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}();r.when("A","SocialShareWidgetConfig","SocialShareWidget").register("SocialShareWidgetTemplating",function(f,a,g){g=g.SocialShareCore;var d=f.$,c=g.Detection.isClipboardAvailable,b=g.Detection.isDesktop,
e=a.excludedChannels;c()||e.push("copy");var h=function(a){return'\x3cspan class\x3d"a-spinner a-spinner-'+a+' a-align-center aok-hidden"\x3e\x3c/span\x3e'};return{build:function(g){var f=g.shareUrl,m=g.socialLinks,n=m===p?{}:m;m=g.shareDataAttributes;var u=g.builtChannels,y=g.kpModalParams,t=g.t;n.email=g.mailToUri;var C='\x3cspan class\x3d"a-button ssf-copy"\x3e\n        \x3cspan class\x3d"a-button-inner"\x3e\n          \x3cinput class\x3d"a-button-input" type\x3d"button"\x3e\n          \x3cspan class\x3d"a-button-text" aria-hidden\x3d"true"\x3e\n            \x3cdiv class\x3d"copy-label"\x3e'+
t.taf_copy_tooltip+"\x3c/div\x3e\n          \x3c/span\x3e\n        \x3c/span\x3e\n      \x3c/span\x3e";!b()&&c()&&1>d(".ssf-feedback").length&&d(document.body).append('\x3cdiv class\x3d"a-changeover ssf-feedback" style\x3d"display:none"\x3e\n          \x3cdiv class\x3d"a-changeover-inner"\x3e\n            \x3ci class\x3d"a-icon a-icon-checkmark-inverse"\x3e\x3c/i\x3e\n            \x3cstrong class\x3d"a-size-medium"\x3e'+t.taf_copy_url_changeover+"\x3c/strong\x3e\n          \x3c/div\x3e\n        \x3c/div\x3e");
var x=function(a){return{title:t["taf_"+a.name+"_tooltip"]||a.label,label:t["taf_"+a.name+"_name"]||a.label}};a.lineMarketplaces.includes(m.marketplaceId)||n.li?e.push("pi"):e.push("li");y||e.push("embed");return{getModal:function(){var a="",b=!0,d=!1,g=p;try{for(var m=Object.entries(u)[Symbol.iterator](),l;!(b=(l=m.next()).done);b=!0){var r=F(l.value,2),I=r[0],G=r[1];if(!e.includes(I)&&"copy"!==I){var w=x(G),y=n[G.name]||G.getSharingUrl();a+='\x3cdiv class\x3d"ssf-channel-h"\x3e\n              \x3ca class\x3d"ssf-channel a-color-base" href\x3d"'+
y+'" title\x3d"'+w.title+'" data-key\x3d"'+I+'"\x3e\n                '+h("medium")+'\n                \x3ci role\x3d"img" aria-label\x3d"'+w.label+'" style\x3d"background-image: url('+G.image+')"\x3e\x3c/i\x3e\n              \x3c/a\x3e\n              \x3cspan\x3e'+w.label+"\x3c/span\x3e\n            \x3c/div\x3e"}}}catch(z){d=!0,g=z}finally{try{!b&&m.return&&m.return()}finally{if(d)throw g;}}b=c()?'\x3cdiv class\x3d"ssf-copy-section a-box a-padding-base a-spacing-top-large"\x3e\n              \x3cdiv class\x3d"link-section"\x3e'+
f.return+'\x3c/div\x3e\n              \x3cdiv class\x3d"copy-button"\x3e'+C+"\x3c/div\x3e\n          \x3c/div\x3e":"";return'\x3ch3 class\x3d"a-spacing-large"\x3e'+t.taf_share_bottom_sheet_title+"\x3c/h3\x3e"+('\x3cdiv class\x3d"ssf-h-icons"\x3e'+a+"\x3c/div\x3e")+b},getPopover:function(){var a="",b=!0,c=!1,d=p;try{for(var g=Object.entries(u)[Symbol.iterator](),f;!(b=(f=g.next()).done);b=!0){var m=F(f.value,2),l=m[0],t=m[1];if(!e.includes(l)){var r=x(t),w=n[t.name]||t.getSharingUrl();a+='\x3cdiv class\x3d"ssf-channel-v"\x3e\n              \x3ca class\x3d"ssf-channel '+
l+' a-color-base" href\x3d"'+w+'" title\x3d"'+r.title+'" data-key\x3d"'+l+'"\x3e\n                '+h("small")+'\n                \x3ci role\x3d"img" aria-label\x3d"'+r.label+'" style\x3d"background-image: url('+t.image+')"\x3e\x3c/i\x3e\n                \x3cspan class\x3d"'+l+'-label"\x3e'+r.label+"\x3c/span\x3e\n              \x3c/a\x3e\n            \x3c/div\x3e"}}}catch(z){c=!0,d=z}finally{try{!b&&g.return&&g.return()}finally{if(c)throw d;}}return""+a},getEasyModeContent:function(){var a='\x3cdiv id\x3d"SocialShare" class\x3d"a-section a-spacing-none"\x3e\x3cdiv class\x3d"a-button-stack a-spacing-none a-js"\x3e\x3cspan class\x3d"s-no-js-hide"\x3e';
var b=!0,c=!1,d=p;try{for(var g=Object.entries(u)[Symbol.iterator](),f;!(b=(f=g.next()).done);b=!0){var h=F(f.value,2),m=h[0],l=h[1];if(!e.includes(m)){var t=x(l),r=n[l.name]||l.getSharingUrl();a+='\x3ca class\x3d"ssf-channel '+m+' a-color-base ssf-easy-mode-channel" href\x3d"'+r+'" title\x3d"'+t.title+'" data-key\x3d"'+m+'"\x3e\n                 \x3cspan class\x3d"a-button a-spacing-none a-button-base s-easy-mode-social-share-button s-easy-mode-social-share-label"\x3e\n                   \x3cspan class\x3d"a-button-inner"\x3e\n                     \x3cinput class\x3d"ssf-channel-v a-button-input" type\x3d"submit"\x3e\n                       \x3cspan aria-hidden\x3d"true" class\x3d"a-button-text"\x3e\n                         \x3cdiv class\x3d"a-section s-easy-mode-action-button-inner aok-nowrap"\x3e\n                           \x3ci class\x3d"ssf-channel-popover-icon" role\x3d"img" aria-label\x3d"'+
t.label+'" style\x3d"background-image: url('+l.image+');"\x3e\x3c/i\x3e\n                           \x3cspan class\x3d"'+m+'-label a-size-base"\x3e'+t.label+"\x3c/span\x3e\n                         \x3c/div\x3e\n                       \x3c/span\x3e\n                     \x3c/input\x3e\n                   \x3c/span\x3e\n                 \x3c/span\x3e\n              \x3c/a\x3e"}}}catch(z){c=!0,d=z}finally{try{!b&&g.return&&g.return()}finally{if(c)throw d;}}return a+"\x3c/span\x3e\x3c/div\x3e\x3c/span\x3e"},
getBottom:function(){var a="",b=!0,c=!1,d=p;try{for(var g=Object.entries(u)[Symbol.iterator](),f;!(b=(f=g.next()).done);b=!0){var m=F(f.value,2),l=m[0],r=m[1];if(!e.includes(l)){var w=x(r),y=n[r.name]||r.getSharingUrl();a+='\x3cdiv class\x3d"ssf-channel-b a-padding-base"\x3e\n              \x3ca class\x3d"ssf-channel '+l+' a-color-base" href\x3d"'+y+'" title\x3d"'+w.title+'" data-key\x3d"'+l+'"\x3e\n                '+h("medium")+'\n                \x3ci role\x3d"img" aria-label\x3d"'+w.label+'" style\x3d"background-image: url('+
r.image+')"\x3e\x3c/i\x3e\n                \x3cspan class\x3d"a-size-base-plus"\x3e'+w.label+"\x3c/span\x3e\n              \x3c/a\x3e\n            \x3c/div\x3e"}}}catch(z){c=!0,d=z}finally{try{!b&&g.return&&g.return()}finally{if(c)throw d;}}return'\x3cdiv class\x3d"a-padding-base ssf-header"\x3e\n          \x3ch4\x3e'+t.taf_share_bottom_sheet_title+'\x3c/h4\x3e\n        \x3c/div\x3e\x3cdiv class\x3d"ssf-scroll"\x3e'+a+"\x3c/div\x3e"},getCustomize:function(){var a=void 0;r.now("SocialShareWidgetCustomizeTemplate").execute(function(b){a=
g.customize?b.getCustomizeBox(t):""});var b='\x3ch3 class\x3d"a-spacing-base a-spacing-top-base"\x3e'+t.taf_share_bottom_sheet_title+"\x3c/h3\x3e",c='\x3cdiv class\x3d"ssf-heading-container"\x3e\x3cimg class\x3d"ssf-back-btn" src\x3d"https://m.media-amazon.com/images/G/01/share-icons/arrow-left.svg"\x3e'+b+"\x3c/div\x3e",e='\x3cdiv class\x3d"a-padding-base a-box ssf-cus-img ssf-no-border" style\x3d"background-image: url('+g.image+')"\x3e'+h("medium")+"\x3c/div\x3e",d=g.caf?'\x3cdiv class\x3d"a-row a-spacing-top-large'+
(g.customize?"":" a-spacing-large")+'"\x3e\n          \x3cdiv class\x3d"a-column a-span9"\x3e\n            \x3cstrong class\x3d"ssf-caf-toggle-label"\x3e'+t.taf_custshare_caf_ingress+'\x3c/strong\x3e\n          \x3c/div\x3e\n          \x3cdiv class\x3d"a-column a-span3 a-text-right a-span-last"\x3e\n            \x3cdiv class\x3d"a-switch-row ssf-caf-toggle"\x3e\n          \x3cinput class\x3d"a-declarative a-switch-input" data-action\x3d"a-switch-input" name\x3d"caf" type\x3d"checkbox"\x3e\n          \x3clabel class\x3d"a-switch-label a-declarative" data-action\x3d"a-switch-label"\x3e\n            \x3cdiv class\x3d"a-switch a-declarative" data-action\x3d"a-switch"\x3e\n              \x3ca class\x3d"a-switch-control" style\x3d"transform: translateX(-1px) translateZ(0px);"\x3e\x3c/a\x3e\n            \x3c/div\x3e\n          \x3c/label\x3e\n        \x3c/div\x3e\n          \x3c/div\x3e\n        \x3c/div\x3e':
"",f='\x3cspan class\x3d"a-button a-button-primary a-spacing-top-small ssf-customize-share-btn"\x3e\n          \x3cspan class\x3d"a-button-inner"\x3e\n            \x3cinput class\x3d"a-button-input" type\x3d"button" aria-labelledby\x3d"ssf-customize-share-btn"\x3e\n            \x3cspan class\x3d"a-button-text" aria-hidden\x3d"true" id\x3d"ssf-customize-share-btn"\x3e\n              '+g.shareLabel+"\n              "+h("small")+"\n            \x3c/span\x3e\n          \x3c/span\x3e\n        \x3c/span\x3e";
return'\x3cdiv class\x3d"a-padding-base ssf-customize-container-one"\x3e'+b+e+d+a+f+"\x3c/div\x3e"+(g.customize?'\x3cdiv class\x3d"a-padding-base ssf-customize-container-two aok-hidden"\x3e'+c+e+d+'\x3cdiv class\x3d"a-row a-spacing-top-base a-padding-base ssf-tabs"\x3e\x3c/div\x3e'+f+"\x3c/div\x3e":"")}}}}});"use strict";r.when("jQuery","SocialShareWidget").register("SocialShareWidgetTiny",function(f,a){var g=a.SocialShareCore.Metrics;return{fetch:function(a){var c=a.data,b=a.callback;if(!c.csrfToken||
!c.gcmToken||!c.url)return g.logCounter("Tiny.Unavailable"),g.startTimer("Tiny"),b();f.ajax("/conversations/sharetinyurl",{type:"POST",contentType:"application/json;charset\x3dUTF-8",data:JSON.stringify(c),success:function(a){g.logCounter("Desktop.Tiny.Response");g.stopTimer("Tiny");b(a.data&&a.data.url)},error:function(){g.logCounter("Desktop.Tiny.Error");g.stopTimer("Tiny");b()}})}}});"use strict";r.when("A","SocialShareWidget").register("SocialShareWidgetCustomize",function(h,a){a=a.SocialShareCore;
var g=h.$,d=a.ShareSheet,c=a.Url,b=a.Metrics,e=a.Constants,n=a.Detection,m=b.getMetricName(g,e.customize),l=f.location.protocol+"//",w=h.constants.HIDE_CLASS;b.startTimer(m);var x=function(){},u=function(){},y={};try{(function(){var a={clear:function(){this.values={}},isEmpty:function(){return g.isEmptyObject(this.values)},values:{},unset:function(a){delete this.values[a.id]},set:function(a){this.values[a.id]=a},currentImage:"",productImageProperties:{width:0,height:0}},C=void 0,K=void 0;r.when("a-button").execute(function(a){return C=
a});r.when("SocialShareWidgetTiny").execute(function(a){return K=a});h.on("a:sheet:afterHide:ssf-customize-bottom-sheet",function(b){b.sheet.getContentContainer().remove();a.clear()});h.on("a:sheet:afterShow:ssf-customize-bottom-sheet",function(a){y.cafSwitch||(a=Math.round(f.innerHeight*(700>f.innerHeight?.2:.25)),g(".ssf-cus-img").css({height:a}))});u=function(a){var b=a.productImage,c=a.price,e=a.rating,d=a.text,g=d===p?"React to this item with an emoji":d,f=a.caf,q=a.cafSwitch,h=b.match(/([\w\d_+-]*)\.?[^\\\/]*$/i);
a=h[1];d=b.match(/\.[0-9a-z]+$/i)[0];h=b.replace(h[0],"");b=decodeURIComponent(b).match(/([\w\d_+-]+)\.png\|/g);f=f&&b&&0<b.length;e=B(g,e,q,f);g="._SR450,315_AC_SR450,180,0,C_SR450,"+(q?320:250)+",0,T";c=c?"_ZA"+encodeURIComponent(encodeURIComponent(c))+",20,180,1000,1000,AmazonEmber,13,0,0,0":"";f&&(g="._CLa|450,350|"+b+"0,0,450,250+0,0,450,250_T");return""+h+a+g+c+e+d};var B=function(a){var b=1<arguments.length&&arguments[1]!==p?arguments[1]:"",c=arguments[3];if(2<arguments.length&&arguments[2]!==
p&&arguments[2]){var e=a.length,d=45<e?150:205;e=45<e?200:235;var g=260;c&&(d+=45,e+=40,g+=40);b=b?"_PIStarRating"+b+",TopLeft,16,"+d:"";b=n.isRTL()?b+("_ZA"+encodeURIComponent(encodeURIComponent(a))+",20,"+e+",420,420,AmazonEmber,13,0,0,0__PIcaf-emojis,TopLeft,12,"+g):b+("_ZA"+encodeURIComponent(encodeURIComponent(a))+",20,"+e+",1000,500,AmazonEmber,13,0,0,0__PIcaf-emojis,TopLeft,12,"+g)}else b=b?"_PIStarRating"+b+",TopLeft,290,"+(c?250:205):"";return b},A=function(a){g(".ssf-cus-img").css("background-image",
'url("'+a+'")')},v=function(b){var c=b.productImage;b.cafSwitch||(b=new Image,b.src=c,b.onload=function(){a.productImageProperties.width=this.width;a.productImageProperties.height=this.height})},k=function(){g(".ssf-cus-img").find(".a-spinner").removeClass(w)},D=function(){g(".ssf-cus-img").find(".a-spinner").addClass(w)},F=function(a){var b=a.shareData;a=a.channelRef;var c=b.shareUrl,e=b.socialLinks;e=e===p?{}:e;a=a?c.getReturnForChannel(a):c.return;return{csrfToken:b.csrfToken,gcmToken:b.gcmToken,
url:a,originalUrl:e.shareframework||b.url||a}},O=function(a,e,f,k,l){g(".ssf-customize-share-btn").find(".a-spinner").addClass(w);C(".ssf-customize-share-btn").enable();e();k&&(e=new URL(f.url),e.searchParams.append("cafId",k),e.searchParams.append("cafASIN",f.shareDataAttributes.asin),f.shareUrl=new c(e.toString(),f.refId));e=F({shareData:f});K.fetch({data:e,callback:function(c){f.tinyUrl=c;l&&l();c=h.extend({channelSelectCB:function(){k&&h.trigger("ssf:event:caf-share-complete-success",f)}},f);
(new d(c)).launch(function(){h.delay(function(b){a(f)},100);k?(b.logCounter(m,"CAF.ShareSheetOpen"),b.logCounterRefactor("CAF.ShareSheetOpen",f.shareDataAttributes.ingress)):(b.logCounter(m,"ShareSheetOpen"),b.logCounterRefactor("ShareSheetOpen",f.shareDataAttributes.ingress))})}})},I=function(a,c){var e=a.cafAapiCsrfToken,d=a.shareDataAttributes,f=d.ingress;a=""+l+a.aapiBaseUrl+"/custom/consultafriendcontracts/marketplaces/"+d.marketplaceId+"/consultafriend/feedback-request/"+d.asin;b.logCounter(m,
"CAF.createCAFID.called");b.logCounterRefactor("CAF.createCAFID.called",f);g.ajax({url:a,type:"POST",headers:{"Accept-Language":"en-US",Accept:'application/vnd.com.amazon.api+json; type\x3d"aapi.consultafriendcontracts.custom.consult-a-friend.feedback-request.response/v1"',"x-api-csrf-token":e,"Content-Type":"application/x-www-form-urlencoded"},xhrFields:{withCredentials:!0},success:function(a){c(a.entity&&a.entity.cafId)},error:function(){b.logCounter(m,"CAF.createCAFID.failed");b.logCounterRefactor("CAF.createCAFID.failed",
f);c()}})},G=function(a,c){var e=a.locale,d=a.shareDataAttributes,f=d.ingress;g.ajax({url:""+l+a.aapiBaseUrl+"/custom/socialshareapicontracts/marketplaces/"+d.marketplaceId+"/products/"+d.asin+"/shareframework/productshareableattributes?locale\x3d"+e+"\x26type\x3d"+a.productType,type:"GET",headers:{"Accept-Language":e,Accept:'application/vnd.com.amazon.api+json; type\x3d"aapi.socialshareapicontracts.custom.ssapis.product.shareable.attributes.response/v1"',"x-api-csrf-token":a.shareAapiCsrfToken,"Content-Type":"application/x-www-form-urlencoded"},
xhrFields:{withCredentials:!0},success:function(a){b.logCounter(m,"FetchTabsSuccess");b.logCounterRefactor("FetchTabsSuccess",f);c(R(a))},error:function(){b.logCounter(m,"FetchTabsFail");b.logCounterRefactor("FetchTabsFail",f);c([])}})},R=function(a){return(a=a.entity)&&"SUCCEEDED"===a.status?a.tabs.map(function(a){var b={id:a.id,heading:a.shortDisplayName,text:a.longDisplayName,isQuote:!0};a.params&&(b.values=Object.values(a.params)[0],b.isQuote=!1);return b}):[]},H=function(a,c,e){var d=a.shareDataAttributes,
f=d.ingress;g.ajax({url:""+l+a.aapiBaseUrl+"/custom/socialshareapicontracts/marketplaces/"+d.marketplaceId+"/products/"+d.asin+"/shareframework/generatecustomizedimage",type:"POST",data:c,headers:{"Accept-Language":a.locale,Accept:'application/vnd.com.amazon.api+json; type\x3d"aapi.socialshareapicontracts.custom.ssapis.product.generate.customized.image.response/v1"',"x-api-csrf-token":a.shareAapiCsrfToken,"Content-Type":"application/x-www-form-urlencoded"},xhrFields:{withCredentials:!0},success:function(a){b.logCounter(m,
"generateCustomizeImageSuccess");b.logCounterRefactor("generateCustomizeImageSuccess",f);e(a)},error:function(a){b.logCounter(m,"generateCustomizeImageFail");b.logCounterRefactor("generateCustomizeImageFail",f);e(a)}})},z=function(c,e){var d=c.shareAapiCsrfToken,f=c.aapiBaseUrl,h=c.locale,k=c.shareDataAttributes;c=k.marketplaceId;var q=k.asin,n=k.ingress;if(a.isEmpty())return e({});k=encodeURIComponent(a.currentImage);g.ajax({url:""+l+f+"/custom/socialshareapicontracts/marketplaces/"+c+"/products/"+
q+"/shareframework/externalizecustomizedimage?customizedImageUrl\x3d"+k,type:"PUT",headers:{"Accept-Language":h,Accept:'application/vnd.com.amazon.api+json; type\x3d"aapi.socialshareapicontracts.custom.ssapis.product.externalize.customized.image.response/v1"',"x-api-csrf-token":d,"Content-Type":"application/x-www-form-urlencoded"},xhrFields:{withCredentials:!0},success:function(a){e(a)},error:function(){b.logCounter(m,"externalizeImageFail");b.logCounterRefactor("externalizeImageFail",n);e({})}})};
x=function(d,f,l){y={productImage:d.productImage||d.image,rating:d.starRating,caf:d.caf,cafSwitch:d.cafSwitch,text:d.t.taf_custshare_caf_recipientemoji};var n=function(){var b=a.values,c=b.BackgroundImageTab,e=b.DeviceCoverImageTab;b=b.BookQuotesTab;var f=a.productImageProperties,g=f.width;f=f.height;return{productImageUrl:d.productImage,starRating:d.starRating||"",numberOfReviews:d.numberOfReviews||"",backgroundImagePhysicalId:(c===p?{}:c).physicalId||"",deviceCoverImagePhysicalId:(e===p?{}:e).physicalId||
"",bookQuote:(b===p?{}:b).value||"",productImageWidth:g===p?"":g,productImageHeight:f===p?"":f}},q=function(){var b=a.values,c=b.BackgroundImageTab;c=c===p?{}:c;var f=b.DeviceCoverImageTab;f=f===p?{}:f;b=b.BookQuotesTab;b=(b===p?{}:b).value||"";return{backgroundImagePhysicalId:c.physicalId||"",deviceCoverImagePhysicalId:f.physicalId||"",hasQuote:0<b?e.TRUE:e.FALSE,isCustomizedExperienceEnabled:d.customize?e.TRUE:e.FALSE,isCustomized:c.physicalId||f.physicalId||b?e.TRUE:e.FALSE}},t=d.shareDataAttributes.ingress;
a.currentImage=u(y);A(u(y));v(y);g(".ssf-customize-share-btn").click(function(){C(".ssf-customize-share-btn").isEnabled()&&(g(".ssf-customize-share-btn").find(".a-spinner").removeClass(w),C(".ssf-customize-share-btn").disable(),y.cafSwitch?(b.logCounter(m,"CAF.shareClick"),b.logCounterRefactor("CAF.shareClick",t),b.startTimer("CAF.fetchCAFAndTinyURL"),I(d,function(a){O(f,l,d,a,function(){b.stopTimer("CAF.fetchCAFAndTinyURL")})})):function(){var a=q();b.logCounter(m,"shareClick");b.logCounterRefactor("shareClick",
t);"true"===a.isCustomized&&(b.logCounter(m,"shareClickCustomized"),b.logCounterRefactor("shareClickCustomized",t));z(d,function(g){if((g=g.entity)&&g.physicalId){b.logCounter(m,"externalizeImageSuccess");b.logCounterRefactor("externalizeImageSuccess",t);var k=new URL(d.url);k.searchParams.append("cspi",g.physicalId);d.shareUrl=new c(k.toString(),d.refId,d.customize?"T3":p)}var n=d;g=n.shareDataAttributes;k=n.treatment;k=k===p?"":k;n=n.weblab;n=n===p?"":n;d=h.extend({customizeShareCSAData:a},d);b.logCSAEvent(e.CSA_HIT_TYPE.CUSTOMIZE_SHARE,
{channel:e.EMPTY_STRING,refMarker:d.shareUrl.refMarker.click,shareDataAttributes:g,treatment:k,weblab:n,customizeShareCSAData:a});O(f,l,d)})}())});h.on("a:switch:caf:on",function(a){y.cafSwitch=!0;b.logCounter(m,"CAF.switchOn");b.logCounterRefactor("CAF.switchOn",t);A(u(y))});h.on("a:switch:caf:off",function(a){y.cafSwitch=!1;b.logCounter(m,"CAF.switchOff");b.logCounterRefactor("CAF.switchOff",t);A(u(y))});g("#ssf-customize-share").click(function(){var a=this;C(this).isEnabled()&&(b.logCounter(m,
"CustomizeButtonClick"),b.logCounterRefactor("CustomizeButtonClick",t),C(this).disable(),G(d,function(b){r.now("SocialShareWidgetCustomizeTemplate").execute(function(c){g(".ssf-tabs").html(c.getTabs(d,b));C(a).enable();b.forEach(function(a){var b=".ssf-tab-"+a.id+" .ssf-options-box";g(b).click(function(a){a=g(a.currentTarget).data("value");var c=g(this).hasClass("active");g(b).removeClass("active");c?K(a):(x(a),g(this).addClass("active"))})})});g(".ssf-customize-container-one").addClass(w);g(".ssf-customize-container-two").removeClass(w).addClass("ssf-customize-transition")}))});
var x=function(c){A();k();a.set(c);var e=n();b.logCounter(m,c.id+"Select");b.logCounterRefactor(c.id+"Select",t);H(d,e,function(b){(b=b.entity)&&"SUCCEEDED"===b.status&&(b=b.customizedImage.url,a.currentImage=b,v(b),A(b),D())})},K=function(c){A();k();b.logCounter(m,c.id+"Unselect");b.logCounterRefactor(c.id+"Unselect",t);a.unset(c);a.isEmpty()?(c=u(y),a.currentImage=c,A(c),D()):(c=n(),H(d,c,function(b){(b=b.entity)&&"SUCCEEDED"===b.status&&(b=b.customizedImage.url,a.currentImage=b,v(b),A(b),D())}))};
g(".ssf-back-btn").click(function(){b.logCounter(m,"BackButtonClick");b.logCounterRefactor("BackButtonClick",t);g(".ssf-customize-container-two").addClass(w);g(".ssf-customize-container-one").removeClass(w).addClass("ssf-customize-transition-back");a.clear();A(u(y))});r.when("a-switch").execute(function(a){g(".ssf-caf-toggle-label").click(function(){a.getSwitch(g(".ssf-caf-toggle")).toggle()})})}})()}catch(t){b.logCounter(m,"Error"),b.logLoad("Error"),b.logFatal("Error loading Customize widget, Share Framework AUI: "+
t.toString())}finally{b.logCounter(m,"Render"),b.logLoad("Render"),b.stopTimer(m)}return{init:x,getImage:u}});"use strict";r.when("A").register("SocialShareWidgetCustomizeTemplate",function(f){var a=function(a){return'\x3cdiv class\x3d"ssf-options-box-container"\x3e'+a.values.map(function(b){var c=f.extend(b,{id:a.id});b={val:c,background:b.url};a.isQuote&&(b=f.extend(b,{center:!0,width:150,content:c.displayText,background:p}));c=b.content;c=c===p?"":c;var d=b.width,e=d===p?100:d,g=b.background;d=
b.center;d=d===p?!1:d;b=b.val;e='style\x3d"width: '+e+"px;background-image: url("+(g===p?"":g)+");background-size: "+e+"px "+e+'px;"';g="data-value\x3d'"+JSON.stringify(b)+"'";return'\x3cdiv class\x3d"a-box ssf-options-box" aria-label\x3d\''+(b.label||"")+"' "+g+" "+e+"\x3e"+(d?'\x3cdiv class\x3d"a-box-inner a-text-center ssf-q-text"\x3e'+c+"\x3c/div\x3e":c)+"\x3c/div\x3e"}).join("")+"\x3c/div\x3e"},g=function(a){var b=2<arguments.length&&arguments[2]!==p?arguments[2]:!1;return'\x3cli class\x3d"a-tab-heading '+
(b?"a-active":"")+'" data-a-tab-name\x3d"ssf-tab-'+a+'" role\x3d"presentation"\x3e\n              \x3ca href\x3d"#" role\x3d"tab" aria-selected\x3d"'+(b?"true":"false")+'" '+(b?"":'tabindex\x3d"-1"')+"\x3e"+(1<arguments.length&&arguments[1]!==p?arguments[1]:"")+"\x3c/a\x3e\n            \x3c/li\x3e"},d=function(a){return'\x3cdiv data-a-name\x3d"ssf-tab-'+a+'" class\x3d"ssf-tab-'+a+" a-box a-box-tab a-tab-content "+(3<arguments.length&&arguments[3]!==p&&arguments[3]?"":"a-hidden")+'" role\x3d"tabpanel" tabindex\x3d"0"\x3e\n              \x3ch4 class\x3d"a-text-normal a-spacing-base"\x3e'+
(2<arguments.length&&arguments[2]!==p?arguments[2]:"")+"\x3c/h4\x3e\n              "+(1<arguments.length&&arguments[1]!==p?arguments[1]:"")+"\n            \x3c/div\x3e"},c=function(){return(0<arguments.length&&arguments[0]!==p?arguments[0]:[]).map(function(a){a=a.replace(/"|”|“/g,"");return{displayText:"“"+a+"”",value:a}})};return{getTabs:function(b,e){var f=b.popularHighlightStrings;if(!e.length)return"";var h="",l="",p=-1;e.forEach(function(b,e){b.isQuote&&(b.values=c(f));if(!b.values.length)return"";
-1===p&&(p=e);e=e===p;h+=g(b.id,b.heading,e);l+=d(b.id,a(b),b.text,e)});return'\x3cdiv class\x3d"a-tab-container a-size-small"\x3e'+('\x3cul data-action\x3d"a-tabs" class\x3d"a-tabs a-declarative" role\x3d"tablist" data-a-tabs\x3d"{"name": "customize-tabs"}"\x3e\n        '+h+"\x3c/ul\x3e"+l)+"\x3c/div\x3e"},getCustomizeBox:function(a){return'\x3cdiv class\x3d"a-box a-color-alternate-background a-spacing-top-large a-padding-base ssf-customize-box"\x3e\n      '+('\x3ch5 class\x3d"a-size-small a-spacing-micro"\x3e'+
a.taf_custshare_customizelong+"\x3c/h5\x3e")+('\x3cp class\x3d"a-size-small a-color-secondary"\x3e'+a.taf_custshare_customizedesc+"\x3c/p\x3e")+('\x3cspan class\x3d"a-button a-button-small" id\x3d"ssf-customize-share"\x3e\n      \x3cspan class\x3d"a-button-inner"\x3e\n        \x3cbutton class\x3d"a-button-text" type\x3d"button"\x3e'+a.taf_custshare_customizeshort+"\x3c/button\x3e\n      \x3c/span\x3e\n    \x3c/span\x3e")+"\n    \x3c/div\x3e"}}})});
/* ******** */
